pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir '.'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out SCM'
                checkout scm
            }
        }

        stage('Format Code') {
            steps {
                echo 'formatting code'
                sh 'bash pbp/bin/format_code.sh'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests'
                echo 'this stage is running a test'
            }
        }
        stage('Build'){
            steps{
                //echo 'Build wheel'
                sh 'bash pbp/bin/build_wheel.sh'
            }
        }
    }

    stages{
        stage('Build docker'){
            steps{
                echo 'Building docker image'
                sh 'docker build -t demo_project:latest .'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}